# Products data - IndiaMART reference
# slug is used in URL: /services/product/<slug>

PRODUCTS = {
    "cng-cylinder-testing": {
        "name": "Cng Cylinder Testing Equipments",
        "slug": "cng-cylinder-testing",
        "division": "HYDROTEST MACHINE",
        "division_id": "hydrotest",
        "short_desc": "Complete CNG cylinder testing plant — hydropump, water jacket, ultrasonic roller, fire stand, degassing stand, trolley, control panel & more.",
        "description": "We provide complete CNG cylinder testing equipments including: Hydropump, Water Jacket, Ultrasonic Roller Machine, Fire Stand, Cylinder Vice, Oil Remove Stand, Hot Air Blower, Degassing Stand with Vent Pipe & Accessories, Trolley, Control Panel with 2 Pressure Gauges, Paint Stand Ring, Air Compressor 90L, Metal Writing Machine, and Weighing Machine. CYLINDER TYPE: CNG | USAGE: TESTING | INSPECTION TYPE: INTERNAL AND EXTERNAL VISUAL INSPECTION | PRODUCT TYPE: CNG CYLINDER | TESTING METHOD: WATER JACKET TYPE | INSPECTION STANDARD: ISO.",
        "price": "₹10,00,000/Piece",
        "image": "image/cngmanufacture.jpg",
    },
    "cylinder-testing-jacket-24": {
        "name": "24 Inch Cylinder Testing Jacket",
        "slug": "cylinder-testing-jacket-24",
        "division": "HYDROTEST MACHINE",
        "division_id": "hydrotest",
        "short_desc": "Mild Steel, Industrial use, Polished. Protective casing for pressure testing.",
        "description": "A 24-inch cylinder testing jacket is a protective casing designed to encase cylindrical specimens during pressure testing. It ensures uniform pressure distribution and safeguards against potential hazards during the testing process. Material: Mild Steel | Usage: Industrial | Color: Green | Surface: Polished | Rust Proof: Yes.",
        "price": "₹1,25,000/Piece",
        "image": "image/waterjacket.jpg",
    },
    "ms-cylinder-vice": {
        "name": "MS Cylinder Vice",
        "slug": "ms-cylinder-vice",
        "division": "HYDROTEST MACHINE",
        "division_id": "hydrotest",
        "short_desc": "Sturdy clamping tool for cylindrical objects. Mild Steel, Blue, Rust Proof.",
        "description": "An MS (mild steel) cylinder vice is a sturdy clamping tool designed to securely hold cylindrical objects during machining or assembly. Its robust construction ensures stability and precision. Usage: Industrial | Color: Blue | Rust Proof: Yes | Water Resistance: Yes | Material: Mild Steel.",
        "price": "₹25,000/Piece",
        "image": "image/manufacture.jpg",
    },
    "hydraulic-rolling-machine": {
        "name": "Hydraulic Rolling Machine",
        "slug": "hydraulic-rolling-machine",
        "division": "HYDROTEST MACHINE",
        "division_id": "hydrotest",
        "short_desc": "20 Ton capacity, Mild Steel, Industrial. Precision metal forming.",
        "description": "A hydrosonic rolling machine utilizes high-pressure water jets to shape and form materials with precision. Capacity: 20 Ton | Material: Mild Steel | Surface: Polished | Usage: Industrial | Rust Proof: Yes.",
        "price": "₹55,000/Piece",
        "image": "image/roller.jpeg",
    },
    "cng-cylinder-bracket": {
        "name": "CNG Cylinder Bracket",
        "slug": "cng-cylinder-bracket",
        "division": "HYDROTEST MACHINE",
        "division_id": "hydrotest",
        "short_desc": "Mild Steel, Blue, Polished. Cylinder tilting rack drying & oil removal stand.",
        "description": "Upgrade your workshop with our Cylinder Tilting Rack Drying and Oil Removal Stand. Features adjustable tilting mechanism for optimal drying and effective oil removal. Material: Mild Steel | Color: Blue | Finishing: Polished | Use: Cylinder Bracket.",
        "price": "₹875/Piece",
        "image": "image/cylinderbracket.jpg",
    },
    "eot-cranes": {
        "name": "Single Girder EOT Cranes",
        "slug": "eot-cranes",
        "division": "HYDROTEST MACHINE",
        "division_id": "hydrotest",
        "short_desc": "10 Ton capacity, Mild Steel, I-beam and pillar setup for CNG facilities.",
        "description": "Single Phase Crane with robust I-beam and pillar setup for superior load handling. Ideal for CNG testing facilities. Capacity: 10 Ton | Color: Yellow | Material: Mild Steel | Rust proof: Yes.",
        "price": "₹75,000/Piece",
        "image": "image/manufacture.jpg",
    },
    "ms-cng-cylinder-stand": {
        "name": "MS CNG Cylinder Stand",
        "slug": "ms-cng-cylinder-stand",
        "division": "HYDROTEST MACHINE",
        "division_id": "hydrotest",
        "short_desc": "Gas cylinder stand, Mild Steel, secure storage for CNG cylinders.",
        "description": "CNG Stand designed for secure and stable storage of CNG cylinders. Material: Mild Steel | Color: Blue | Rust Proof: Yes | Water Resistance: Yes.",
        "price": "₹1,500/Piece",
        "image": "image/cylinderbracket.jpg",
    },
    "hydraulic-testing-station": {
        "name": "Hydraulic Cylinder Testing Station",
        "slug": "hydraulic-testing-station",
        "division": "HYDROTEST MACHINE",
        "division_id": "hydrotest",
        "short_desc": "CNG, MS, 7 HP, Water jacket type. Complete testing station.",
        "description": "Specialized equipment to evaluate performance and integrity of hydraulic cylinders. Gas Type: CNG | Material: MS | Power: 7 HP | Test Method: Water jacket type.",
        "price": "₹12,50,000/Piece",
        "image": "image/cnghydro.jpeg",
    },
    "air-compressor-90l": {
        "name": "90L Industrial Air Compressor",
        "slug": "air-compressor-90l",
        "division": "HYDROTEST MACHINE",
        "division_id": "hydrotest",
        "short_desc": "5 HP, Air Cooled, Industrial. High-volume air for tools & machinery.",
        "description": "Powerful machine to compress and deliver high volumes of air for manufacturing, construction, and automotive industries. Motor Power: 5 HP | Cooling: Air Cooled | Usage: Industrial | Rust Proof: Yes.",
        "price": "₹55,000/Piece",
        "image": "image/manufacture.jpg",
    },
    "hydraulic-pressure-machine": {
        "name": "Hydraulic Pressure Machine",
        "slug": "hydraulic-pressure-machine",
        "division": "HYDROTEST MACHINE",
        "division_id": "hydrotest",
        "short_desc": "40 LPM, 15 Bar. Control panel with dual pressure gauges.",
        "description": "Control Panel Setup with dual pressure gauges for precise monitoring. Usage: Pressure Testing Industry | Power: AC | Flow Rate: 40 LPM | Pressure: 15 Bar | Material: Mild Steel.",
        "price": "₹1,45,000/Piece",
        "image": "image/pressure.jpeg",
    },
    "ultrasonic-roller": {
        "name": "Ultrasonic Machine Roller",
        "slug": "ultrasonic-roller",
        "division": "HYDROTEST MACHINE",
        "division_id": "hydrotest",
        "short_desc": "Mild Steel, Blue. Ultrasonic automatic roller for CNG testing.",
        "description": "Ultrasonic Automatic Roller Machine for precise and efficient material handling. Material: Mild Steel | Color: Blue | Type: Industrial Roller | Finishing: Polished | Rust Proof: Yes.",
        "price": "₹1,25,000/Piece",
        "image": "image/roller.jpeg",
    },
    "water-cooling-jacket-24": {
        "name": "24 Inch Water Cooling Jacket",
        "slug": "water-cooling-jacket-24",
        "division": "HYDROTEST MACHINE",
        "division_id": "hydrotest",
        "short_desc": "Mild Steel, 24\" diameter. Optimal cooling for CNG pressure testing.",
        "description": "Water Jacket designed for optimal cooling and accurate results during CNG pressure tests. Material: Mild Steel | Color: Blue | Diameter: 24 inch | Rust Proof: Yes.",
        "price": "₹1,25,000/Piece",
        "image": "image/waterjacket.jpg",
    },
    "iron-water-cooling-jacket": {
        "name": "Iron Water Cooling Jacket",
        "slug": "iron-water-cooling-jacket",
        "division": "HYDROTEST MACHINE",
        "division_id": "hydrotest",
        "short_desc": "Iron, Industrial, Polished. Temperature control for pressure tests.",
        "description": "Water Jacket for optimal cooling during pressure tests. Material: Iron | Usage: Industrial | Color: Green | Surface: Polished | Rust Proof: Yes.",
        "price": "₹1,45,000/Piece",
        "image": "image/ironwatercoolingjacket.jpg",
    },
    "cylinder-roller-motor": {
        "name": "Cylinder Roller Motor Machine",
        "slug": "cylinder-roller-motor",
        "division": "HYDROTEST MACHINE",
        "division_id": "hydrotest",
        "short_desc": "Mild Steel, motorized. Efficient rotation for CNG cylinder inspection.",
        "description": "CNG Cylinder Roller Machine with powerful motor for efficient and smooth rotation. Material: Mild Steel | Color: Blue | Usage: Industrial | Rust Proof: Yes.",
        "price": "₹65,000/Piece",
        "image": "image/roller.jpeg",
    },
    "hot-air-blower": {
        "name": "Hot Air Blower",
        "slug": "hot-air-blower",
        "division": "HYDROTEST MACHINE",
        "division_id": "hydrotest",
        "short_desc": "4 HP, Mild Steel. Motorized blower for rapid, even heat distribution.",
        "description": "Hot Air Heating System with motorized blower for rapid, even heat distribution. Power: 4 HP | Color: Blue | Usage: Industrial | Material: Mild Steel | Rust Proof: Yes.",
        "price": "₹42,000/Piece",
        "image": "image/hydroairblower.jpeg",
    },
    "degasser-2ton": {
        "name": "2 Ton Degasser Machine",
        "slug": "degasser-2ton",
        "division": "HYDROTEST MACHINE",
        "division_id": "hydrotest",
        "short_desc": "Iron, Blue. Degassing stand with vent pipe & accessories for CNG cylinders.",
        "description": "Degassing Stand with vent pipe and essential accessories for safe CNG cylinder degassing. Capacity: 2 Ton | Material: Iron | Color: Blue | Rust Proof: Yes | Water Resistance: Yes.",
        "price": "₹28,000/Piece",
        "image": "image/manufacture.jpg",
    },
    "pressure-gauge": {
        "name": "Stainless Steel Pressure Gauge",
        "slug": "pressure-gauge",
        "division": "HYDROTEST MACHINE",
        "division_id": "hydrotest",
        "short_desc": "2 inch / 50 mm, Digital, 25 Bar. Control panel pressure gauge.",
        "description": "Control panel pressure gauge for measuring and displaying pressure of fluids or gases. Dial: 2 inch/50 mm | Display: Digital | Pressure: Gauge | Range: 25 Bar | Casing: Stainless Steel.",
        "price": "₹45,000/Piece",
        "image": "image/pressure.jpeg",
    },
    "fire-bucket-stand": {
        "name": "Fire Bucket Stand",
        "slug": "fire-bucket-stand",
        "division": "HYDROTEST MACHINE",
        "division_id": "hydrotest",
        "short_desc": "4 Buckets capacity, Mild Steel, Red. Fire suppression for CNG testing.",
        "description": "Fire Stand with sturdy bucket for effective fire suppression. Capacity: 4 Buckets | Material: Mild Steel | Color: Red | Water Resistance: Yes.",
        "price": "₹5,000/Piece",
        "image": "image/safety.jpg",
    },
    "engraving-machine": {
        "name": "Electric Engraving Machines",
        "slug": "engraving-machine",
        "division": "HYDROTEST MACHINE",
        "division_id": "hydrotest",
        "short_desc": "Metal engravers, Semi-automatic. Metal plate marking for CNG testing.",
        "description": "Metal Pen Engraving Machine for precise markings on metal plates. Type: Etching | Usage: Metal Engravers | Automation: Semi-Automatic | Color: Black | Power: Electric.",
        "price": "₹1,500/Piece",
        "image": "image/manufacture.jpg",
    },
    "oil-removed-stand": {
        "name": "Oil Removed Stand",
        "slug": "oil-removed-stand",
        "division": "HYDROTEST MACHINE",
        "division_id": "hydrotest",
        "short_desc": "Stainless Steel, Blue. Oil collection and separation for industrial use.",
        "description": "Specialized equipment to efficiently collect and separate oil from various surfaces or fluids. Material: Stainless Steel | Color: Blue | Rust Proof: Yes | Water Resistance: Yes.",
        "price": "₹25,000/Piece",
        "image": "image/manufacture.jpg",
    },
    "water-tank-jacket": {
        "name": "Water Tank Jacket",
        "slug": "water-tank-jacket",
        "division": "HYDROTEST MACHINE",
        "division_id": "hydrotest",
        "short_desc": "Iron, Industrial. Insulating layer for thermal efficiency of water tanks.",
        "description": "Insulating layer to enhance thermal efficiency of water storage tanks. Material: Iron | Usage: Industrial | Color: Green | Surface: Polished | Rust Proof: Yes.",
        "price": "₹1,25,000/Piece",
        "image": "image/waterjacket.jpg",
    },
    "hydraulic-pump-motor": {
        "name": "Hydraulic Pump Motor",
        "slug": "hydraulic-pump-motor",
        "division": "HYDROTEST MACHINE",
        "division_id": "hydrotest",
        "short_desc": "800 RPM, Cast Iron, 50Hz. Motorized hydraulic pump for CNG cylinder testing.",
        "description": "Motorized Hydraulic Pump for reliable and powerful performance. Speed: 800 RPM | Type: Hydraulic Motor | Material: Cast Iron | Frequency: 50Hz | Usage: Industrial.",
        "price": "₹95,000/Piece",
        "image": "image/hydropump.jpeg",
    },
    "rolling-shutter": {
        "name": "Motorized Rolling Shutter",
        "slug": "rolling-shutter",
        "division": "Rolling Shutter",
        "division_id": "rolling-shutter",
        "short_desc": "Industrial motorized rolling shutter solutions.",
        "description": "Professional motorized rolling shutter solutions for industrial and commercial applications.",
        "price": "Price on Request",
        "image": "image/manufacture.jpg",
    },
    "shed-fabrication": {
        "name": "Industrial Shed Fabrication",
        "slug": "shed-fabrication",
        "division": "Industrial Shed Fabrication Service",
        "division_id": "shed-fabrication",
        "short_desc": "Professional industrial shed fabrication services.",
        "description": "Expert industrial shed fabrication services tailored to your requirements.",
        "price": "Price on Request",
        "image": "image/fabrication.jpeg",
    },
    "warehouse-shed": {
        "name": "Mild Steel Warehouse Shed",
        "slug": "warehouse-shed",
        "division": "Factory Shed",
        "division_id": "factory-shed",
        "short_desc": "Durable MS warehouse shed solutions.",
        "description": "Durable Mild Steel warehouse shed solutions for industrial storage and operations.",
        "price": "Price on Request",
        "image": "image/fabrication1.webp",
    },
    "factory-blue-shed": {
        "name": "Factory Blue Sheds",
        "slug": "factory-blue-shed",
        "division": "Factory Shed",
        "division_id": "factory-shed",
        "short_desc": "Factory shed solutions in blue finish.",
        "description": "Factory shed solutions with blue finish for industrial applications.",
        "price": "Price on Request",
        "image": "image/fabrication1.webp",
    },
    "ultrasonic-flaw-detector": {
        "name": "Ultrasonic Flaw Detector Machine",
        "slug": "ultrasonic-flaw-detector",
        "division": "Ultrasonic Flaw Detector",
        "division_id": "ultrasonic",
        "short_desc": "Industrial ultrasonic flaw detection equipment.",
        "description": "Industrial ultrasonic flaw detection equipment for quality assurance and safety verification.",
        "price": "Price on Request",
        "image": "image/pressure.jpeg",
    },
}

DIVISIONS = [
    {"id": "hydrotest", "name": "HYDROTEST MACHINE", "icon": "fa-cogs"},
    {"id": "rolling-shutter", "name": "Rolling Shutter", "icon": "fa-door-open"},
    {"id": "shed-fabrication", "name": "Industrial Shed Fabrication Service", "icon": "fa-industry"},
    {"id": "factory-shed", "name": "Factory Shed", "icon": "fa-warehouse"},
    {"id": "ultrasonic", "name": "Ultrasonic Flaw Detector", "icon": "fa-search"},
]

def get_products_by_division():
    result = {}
    for slug, p in PRODUCTS.items():
        div_id = p["division_id"]
        if div_id not in result:
            result[div_id] = []
        result[div_id].append(p)
    return result
